INFO:werkzeug: * Running on http://0.0.0.0:3111/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [27/Aug/2021 18:57:38] "GET / HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:3111/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [27/Aug/2021 19:04:40] "GET / HTTP/1.1" 200 -
INFO:app:2020 CNCF Annual Report article retrievied
INFO:werkzeug:127.0.0.1 - - [27/Aug/2021 19:04:43] "GET /1 HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:3111/ (Press CTRL+C to quit)
INFO:app:'KubeCon + CloudNativeCon 2021' article retrievied
INFO:werkzeug:127.0.0.1 - - [27/Aug/2021 19:05:38] "GET /2 HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:3111/ (Press CTRL+C to quit)
INFO:app:'Kubernetes v1.20 Release Notes' article retrievied
INFO:werkzeug:127.0.0.1 - - [27/Aug/2021 19:09:07] "GET /3 HTTP/1.1" 200 -
INFO:app:'2020 CNCF Annual Report' article retrievied
INFO:werkzeug:127.0.0.1 - - [27/Aug/2021 19:09:21] "GET /1 HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:3111/ (Press CTRL+C to quit)
ERROR:app:Exception on /1 [GET]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/maurobenedito/Documents/nd064_course_1-main/project/techtrends/app.py", line 75, in post
    _log("'"+post['title']+"' article retrievied")
  File "/Users/maurobenedito/Documents/nd064_course_1-main/project/techtrends/app.py", line 11, in _log
    now = datetime.now()
AttributeError: module 'datetime' has no attribute 'now'
INFO:werkzeug:127.0.0.1 - - [27/Aug/2021 19:09:42] "GET /1 HTTP/1.1" 500 -
INFO:werkzeug: * Running on http://0.0.0.0:3111/ (Press CTRL+C to quit)
INFO:app:27/08/2021 19:10:12 '2020 CNCF Annual Report' article retrievied
INFO:werkzeug:127.0.0.1 - - [27/Aug/2021 19:10:12] "GET /1 HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:3111/ (Press CTRL+C to quit)
INFO:app:27/08/2021 19:10:51, '2020 CNCF Annual Report' article retrievied
INFO:werkzeug:127.0.0.1 - - [27/Aug/2021 19:10:51] "GET /1 HTTP/1.1" 200 -
